Models/ErrorViewModel.cs
using System;

namespace CRUD_EFCS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pessoa.cs
namespace CRUD_EFCS.Models
{
    public class Pessoa
    {
        public int Id{get;set;}
        public string Nome{get;set;}
        public string SobreNome{get;set;}
        public int Idade{get;set;}        
    }
    
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRUD_EFCS.Models;

namespace CRUD_EFCS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PessoaController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CRUD_EFCS.Models;
using CRUD_EFCS.Database;
using System.Threading.Tasks;

namespace CRUD_EFCS
{
    public class PessoaController: Controller
    {
        private readonly PessoaDBContext _database;
        public PessoaController(PessoaDBContext database)
        {
            _database = database;
        }
        
        public IActionResult Index()
        {           
            var pessoas = _database.Pessoas.ToList();
            return View(pessoas);
        }

        public IActionResult Deletar(int id)
        {
            Pessoa pessoa = _database.Pessoas.First( registro => registro.Id == id);
            _database.Pessoas.Remove(pessoa);
            _database.SaveChanges();
            return RedirectToAction("Index");
        }       

        public IActionResult Editar(int id)
        {
            Pessoa pessoa = _database.Pessoas.First(registro => registro.Id == id);
            return View("Cadastrar",pessoa);            
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Salvar(Pessoa pessoa)
        {
            if (pessoa.Id == 0 )
            {
                _database.Add(pessoa);
            }else
            {
                Pessoa pessoa1 = _database.Pessoas.First(registro => registro.Id == pessoa.Id);
                pessoa1.Nome = pessoa.Nome;
                pessoa1.SobreNome = pessoa.SobreNome;
                pessoa1.Idade = pessoa.Idade; 
            }            
            _database.SaveChanges();
            return RedirectToAction("Index");            
        }        
    }
    
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pessoa/Cadastrar.cshtml
@model CRUD_EFCS.Models.Pessoa;

<h2>Cadastro de Pessoas</h2>   

<form class="form-horizontal" asp-controller="Pessoa" asp-action="Salvar" method="post"> 
    <input type="number" hidden class="form_controle" asp-for="Id">
    <input type="text" class="form-control" asp-for="Nome" placeholder="Nome da Pessoa"> 
    <input type="text" class="form-control" asp-for="SobreNome" placeholder="Sobre Nome da pessoa">
    <input type="number" class="form-control" asp-for="Idade" placeholder="Digite a idade">
    <button class="btn btn-success">Cadastrar</button> 

</form> 

Views/Pessoa/Index.cshtml
@model IEnumerable<CRUD_EFCS.Models.Pessoa>

<h2>Todas as pessoas</h2> 

<a href="/Pessoa/Cadastrar" class="btn btn-success">Nova Pessoa</a> 

<hr> 

@foreach(var pessoa in Model) 

{ 

    <p>Nome: @pessoa.Nome</p> 

    <p>SobreNome: @pessoa.SobreNome</p> 

    <p>Idade: @pessoa.Idade</p> 

    <a href="/Pessoa/Editar/@pessoa.Id" class="btn btn-success">Editar</a> 

    <a href="/Pessoa/Deletar/@pessoa.Id" class="btn btn-danger">Deletar</a> 

    <hr> 

} 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_EFCS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_EFCS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CRUD_EFCS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>